from __future__ import annotations

from typing import Protocol

from eidon_os.domain.knowledge import Company, FileRecord, KnowledgeItem, Person, Project, Relationship


class KnowledgeRepository(Protocol):
    def save_project(self, project: Project) -> None: ...
    def list_projects(self) -> list[Project]: ...

    def save_file(self, file_record: FileRecord) -> None: ...
    def list_files(self) -> list[FileRecord]: ...

    def save_person(self, person: Person) -> None: ...
    def list_people(self) -> list[Person]: ...

    def save_company(self, company: Company) -> None: ...
    def list_companies(self) -> list[Company]: ...

    def save_knowledge(self, item: KnowledgeItem) -> None: ...
    def list_knowledge(self) -> list[KnowledgeItem]: ...

    def save_relationship(self, relationship: Relationship) -> None: ...
    def list_relationships(self) -> list[Relationship]: ...
